### ISSUE TITLE
Cron / schedule paramter issue in trade.js

### ISSUE THREAD

**Issue by WinMinerGMX** [lukeliasi/binance-dca-bot#20]
Hello. So I am trying to set this up and I am running into the following issue and I can no see anything wrong with my cron pattern. It is valid according to crontab.guru. I want to execute a buy at 16:00 (or 4:00pm) every wednesday but the bot seems to not know how to handle the number 16. What am I doing wrong?

Please also see the attached screenshot.

![2021-11-01 16_05_36-Window](https://user-images.githubusercontent.com/34789416/139693868-9025490d-c3fa-405d-8f80-58931710acf0.png)

**Comment by lukeliasi** [comment]
Try wrapping the value in quotes in trades.js, e.g: `schedule: "0 16 * * WED"`

**Comment by WinMinerGMX** [comment]
Thank you for the swift reply.

It's a small detail but I must have overlooked this in the way the cron pattern is typed down in the .env file.

Maybe a little info on the main pages in the trades.js section would be beneficial to future users.

I also noticed that as long as TRADES is not commented out in the .env file the trades in the trade.js file will be ignored.

But anyway thanks for helping me fix the issue. :)

**Comment by lukeliasi** [comment]
Yes good point, I will add the types each value should be in the docs. Thanks.
